### ISSUE TITLE
INFOGRAFIA GESTION DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS#2]
[INFOGRAFIA DE GESTION DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS/files/12457731/INFOGRAFIA.DE.GESTION.DE.PROYECTOS.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
