### ISSUE TITLE
Infografia_GESTION DE PROYECTOS

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS#3]
[Infografia_GESTION DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS/files/12457732/Infografia_GESTION.DE.PROYECTOS.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 19
Debió ser una sola hoja.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
