### ISSUE TITLE
INFOGRAFIA GESTION DE PROYECTOS_MARIA JOSE LOPEZ LEYVA

### ISSUE THREAD

**Issue by MariaJose-1007** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS#4]
[INFOGRAFIA GESTION DE PROYECTOS_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JudithReynaCS/files/12457864/INFOGRAFIA.GESTION.DE.PROYECTOS_MARIA.JOSE.LOPEZ.LEYVA.pdf)

**Comment by DiegoSCP117** [comment]
Calificación: 20

:3

**Comment by josealfredo79** [comment]
bien hecho y revisado...
